---
- hosts: '{{ target }}'
  tasks:
    - name: Change timezone to IST
      become: true
      shell: timedatectl set-timezone Asia/Kolkata

    - name: Update package indices
      become: true
      shell: apt-get update -y

    - name: Install Essential Dependencies curl gnupg
      become: true
      shell: apt-get install curl gnupg -y

    - name: Install Essential Dependencies apt-transport-https
      become: true
      shell: apt-get install apt-transport-https -y

    - name: Add Repository Signing Keys
      become: true
      shell: |
            curl -1sLf "https://keys.openpgp.org/vks/v1/by-fingerprint/0A9AF2115F4687BD29803A206B73A36E6026DFCA" | gpg --dearmor | tee /usr/share/keyrings/com.rabbitmq.team.gpg > /dev/null
            curl -1sLf https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-erlang.E495BB49CC4BBE5B.key | gpg --dearmor | tee /usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg > /dev/null
            curl -1sLf https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-server.9F4587F226208342.key | gpg --dearmor | tee /usr/share/keyrings/rabbitmq.9F4587F226208342.gpg > /dev/null

    - name: Add a Repository (Apt Source List) File
      become: true
      shell: |
            tee /etc/apt/sources.list.d/rabbitmq.list <<EOF
            ## Provides modern Erlang/OTP releases from a Cloudsmith mirror
            ##
            deb [arch=amd64 signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg] https://ppa1.rabbitmq.com/rabbitmq/rabbitmq-erlang/deb/ubuntu noble main
            deb-src [signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg] https://ppa1.rabbitmq.com/rabbitmq/rabbitmq-erlang/deb/ubuntu noble main

            # another mirror for redundancy
            deb [arch=amd64 signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg] https://ppa2.rabbitmq.com/rabbitmq/rabbitmq-erlang/deb/ubuntu noble main
            deb-src [signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg] https://ppa2.rabbitmq.com/rabbitmq/rabbitmq-erlang/deb/ubuntu noble main

            ## Provides RabbitMQ from a Cloudsmith mirror
            ##
            deb [arch=amd64 signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.gpg] https://ppa1.rabbitmq.com/rabbitmq/rabbitmq-server/deb/ubuntu noble main
            deb-src [signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.gpg] https://ppa1.rabbitmq.com/rabbitmq/rabbitmq-server/deb/ubuntu noble main

            # another mirror for redundancy
            deb [arch=amd64 signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.gpg] https://ppa2.rabbitmq.com/rabbitmq/rabbitmq-server/deb/ubuntu noble main
            deb-src [signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.gpg] https://ppa2.rabbitmq.com/rabbitmq/rabbitmq-server/deb/ubuntu noble main
            EOF
    
    - name: Update package indices
      become: true
      shell: apt-get update -y

    - name: Install Erlang packages
      become: true
      shell: apt-get install -y erlang-base \
                        erlang-asn1 erlang-crypto erlang-eldap erlang-ftp erlang-inets \
                        erlang-mnesia erlang-os-mon erlang-parsetools erlang-public-key \
                        erlang-runtime-tools erlang-snmp erlang-ssl \
                        erlang-syntax-tools erlang-tftp erlang-tools erlang-xmerl

    - name: Install rabbitmq-server and its dependencies
      become: true
      shell: apt-get install rabbitmq-server -y --fix-missing

    - name: Set rabbitmq version variable
      become: true
      shell: rabbitmqctl version
      register: rabbitmq_version

    - name: Print rabbitmq version
      debug: 
        var: rabbitmq_version

    - name: Download delayed message exchange plugin
      become: true
      shell: 
        cmd: "curl -1sLf https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v{{ delayed_message_exchange_version }}/rabbitmq_delayed_message_exchange-{{ delayed_message_exchange_version }}.ez | tee /usr/lib/rabbitmq/lib/rabbitmq_server-{{ rabbitmq_version.stdout_lines[0] }}/plugins/rabbitmq_delayed_message_exchange-{{ delayed_message_exchange_version }}.ez > /dev/null"

    - name: Install unzip
      become: true
      shell: apt install unzip -y

    - name: Extract delayed message exchange plugin
      become: true
      shell: 
        cmd: "unzip -o /usr/lib/rabbitmq/lib/rabbitmq_server-{{ rabbitmq_version.stdout_lines[0] }}/plugins/rabbitmq_delayed_message_exchange-{{ delayed_message_exchange_version }}.ez"

    - name: Enable rabbitmq management plugin
      become: true
      shell: rabbitmq-plugins enable rabbitmq_management

    - name: Enable delayed message exchange
      become: true
      shell: rabbitmq-plugins enable rabbitmq_delayed_message_exchange