---
- hosts: "{{ target }}"
  gather_facts: no
  become: yes
  tasks:
    - name: Download OCI Monitoring Agent
      get_url:
        url: "https://objectstorage.{{ ansible_default_ipv4.address | regex_replace('.*\\.(.*)\\.(.*)\\..*', '\\1-\\2') }}.oraclecloud.com/p/monitoring-agent/monitoring-agent-latest.tar.gz"
        dest: /tmp/monitoring-agent-latest.tar.gz
        mode: '0644'

    - name: Extract OCI Monitoring Agent
      unarchive:
        src: /tmp/monitoring-agent-latest.tar.gz
        dest: /opt/
        remote_src: yes
        creates: /opt/oracle/oci-monitoring-agent

    - name: Create monitoring agent directory
      file:
        path: /opt/oracle/oci-monitoring-agent/bin
        state: directory
        mode: '0755'

    - name: Copy monitoring agent config
      copy:
        src: "{{ cloudwatch_agent_config_path }}"
        dest: /opt/oracle/oci-monitoring-agent/bin/config.json
        mode: '0644'

    - name: Install and start OCI monitoring agent service
      systemd:
        name: oci-monitoring-agent
        state: started
        enabled: yes